name: go-ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#env:
#  CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Print info
      run: |
        make env

    - name: Get dependencies
      run: |
        make actionInstall

    - name: test coverage
      run: make actionCoverage
      env:
        PLUGIN_FEISHU_WEBHOOK: ${{ secrets.PLUGIN_FEISHU_WEBHOOK }}
        PLUGIN_FEISHU_SECRET: ${{ secrets.PLUGIN_FEISHU_SECRET }}

    - name: test benchmark
      run: make actionTestBenchmark
      env:
        PLUGIN_FEISHU_WEBHOOK: ${{ secrets.PLUGIN_FEISHU_WEBHOOK }}
        PLUGIN_FEISHU_SECRET: ${{ secrets.PLUGIN_FEISHU_SECRET }}

    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{secrets.CODECOV_TOKEN}}
